"""edit table followers

Revision ID: 72fa0f02ebfd
Revises: e094a9d38ead
Create Date: 2024-02-29 11:06:01.663945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fa0f02ebfd'
down_revision: Union[str, None] = 'e094a9d38ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('following_id', sa.Integer(), nullable=False))
    op.drop_constraint('followers_friend_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['following_id'], ['id'])
    op.drop_column('followers', 'friend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_friend_id_fkey', 'followers', 'users', ['friend_id'], ['id'])
    op.drop_column('followers', 'following_id')
    # ### end Alembic commands ###
