"""change

Revision ID: 1b92f11345f5
Revises: 7e147741286b
Create Date: 2024-03-23 14:59:33.917892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b92f11345f5'
down_revision: Union[str, None] = '7e147741286b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'tweet_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tweets', 'tweet_media_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'tweet_media_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.alter_column('tweets', 'tweet_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
